# Author: Schuy
# Makefile for building tests.

PATHI=include/
PATHU=unity/src/
PATHS=src/
PATHT=test/
PATHB=build/test/
PATHO=build/test/objects/
PATHR=build/test/results/

BUILD_PATHS=$(PATHB) $(PATHO) $(PATHR)

TSRC=$(wildcard $(PATHT)*.c)

COMPILE=gcc -c
LINK=gcc
CFLAGS=-I. -I$(PATHI) -I$(PATHU)

# Define phony so make doesn't attempt to build
.PHONY: test

# Checks test result files and outputs failures and ignores
test: $(BUILD_PATHS) $(RESULTS)
	@echo -e "--------------------\nIGNORES:\n--------------------"
	@echo `grep -s IGNORE $(PATHR)*.txt`
	@echo -e "--------------------\nFAILURES:\n--------------------"
	@echo `grep -s FAIL $(PATHR)*.txt`

tests:$(PATHT)*.c $(PATHS)*.c $(PATHU)unity.c
	$(LINK) $(CFLAGS) $^ -o $@

# Make the necessary directories to run test if they don't exist
$(PATHB):
	mkdir -p $(PATHB)

$(PATHO):
	mkdir -p $(PATHO)

$(PATHR):
	mkdir -p $(PATHR)

